on:
  pull_request:
    branches:
    - 'tornado'
    - 'main'
    types: [closed]

name: Update Task Status to Done

jobs:
  test-transition-issue:
    name: Changing Task Status to Done
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    # Atlassianにログイン
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    # プルリクエストするブランチ名からissue numberを抽出する
    - name: Extract issue number
      id: extract-issue-number
      shell: bash
      run: |
        ISSUE_NUMBER=$(echo ${{ github.head_ref }} | grep -oP "\d+")
        echo "Issue number: $ISSUE_NUMBER"
        echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT

    # 取得したissue numberのissueに対する最初のコメントを取得
    - name: Find comment
      uses: peter-evans/find-comment@v2
      id: find-comment
      with:
        token: ${{ secrets.PAT_TOKEN }}
        issue-number: ${{ steps.extract-issue-number.outputs.issue_number }}
        direction: first

    # 取得したコメントに記載されたJiraタスクIDを抽出する
    - name: Find in commit messages
      id: find
      uses: atlassian/gajira-find-issue-key@master
      with:
        string: ${{ steps.find-comment.outputs.comment-body }}

    # JiraタスクIDのプロパティを取得　
    - name: Get Issue Properties
      uses: frieder/jira-issue-info@v1
      with:
        issue: ${{ steps.find.outputs.issue }}
      id: issue

    # JiraタスクIDが特定できればJiraに対してトランジションを発行　
    - name: Transition task
      uses: atlassian/gajira-transition@master
      # JiraタスクIDがレビューになければスルー
      if: fromJSON(steps.issue.outputs.json).fields.status.name == 'レビュー'
      with:
        # 前のステップのアウトプットを参照
        issue: ${{ steps.find.outputs.issue }}
        transition: 'Done (2)'

    # Issueを閉じる
    - name: Close Issue
      uses: peter-evans/close-issue@v3
      with:
        token: ${{ secrets.PAT_TOKEN }}
        issue-number: ${{ steps.extract-issue-number.outputs.issue_number }}
        comment: Auto-closing issue
